# Generated by Django 4.1.3 on 2023-05-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jukeapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JukeUser',
        ),
    ]
