# Generated by Django 3.2 on 2023-06-01 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jukeapi', '0003_jukeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='jukeuser',
            name='title',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
